name: CI/CD backend 

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOCKER_USERNAME: sebastianolivares 
      DOCKER_PASSWORD: dckr_pat__U8JJbyFLBgiuTBZ9bSlU_ipRLE 
      IMAGE_NAME: backend-app 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Push Docker Image to Registry
        run: |
          echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker tag ${{env.IMAGE_NAME}} ${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:latest
          docker push ${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:latest

